apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - constraint.yaml
  - template.yaml

patches: 
  - path: patch.yaml 
    target: 
      group: constraints.gatekeeper.sh
      version: v1beta1
      kind: ""
      name: ""